http:
  middlewares:
    middlewares-websocket:
      headers:
        accessControlAllowHeaders:
          - Origin
          - Content-Type
          - Accept
          - Authorization
          - X-Requested-With
          - X-Forwarded-For
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlAllowOriginList:
          - "*"
        accessControlAllowCredentials: true
