services:
  # AirDC++ - DC++ Client Web Interface
  airdcpp:
    image: romancin/airdcpp-webclient
    container_name: airdcpp
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["media", "dcpp", "all"]
    networks:
      - t3_proxy
    ports:
      - "5600:5600"   # Web UI
      - "5601:5601"   # API / alternate UI
      - "21248:21248"       # TCP active connection port
      - "21248:21248/udp"   # UDP search / transfers
      - "21249:21249"       # TCP TLS connections
    volumes:
      - $DOCKERDIR/appdata/airdcpp:/root/.airdcpp
      - $DOWNLOADSDIR:/Downloads
      - $MEDIADIR/Comics:/Share
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth Bypass
      - "traefik.http.routers.airdcpp-rtr-bypass.entrypoints=websecure"
      - "traefik.http.routers.airdcpp-rtr-bypass.rule=Host(`airdcpp.$DOMAINNAME_HS`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)"
      - "traefik.http.routers.airdcpp-rtr-bypass.priority=100"
      # HTTP Routers Auth
      - "traefik.http.routers.airdcpp-rtr.entrypoints=websecure"
      - "traefik.http.routers.airdcpp-rtr.rule=Host(`airdcpp.$DOMAINNAME_HS`)"
      - "traefik.http.routers.airdcpp-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.airdcpp-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.airdcpp-rtr.service=airdcpp-svc"
      - "traefik.http.routers.airdcpp-rtr-bypass.service=airdcpp-svc"
      - "traefik.http.services.airdcpp-svc.loadbalancer.server.port=5600"
      # UPDATE IMAGE
      - "com.centurylinklabs.watchtower.enable=true"
      # Homepage Setup
      # - homepage.group=Downloaders
      # - homepage.name=AirDC++
      # - homepage.icon=cloud-download.png
      # - homepage.href=http://.$DOMAINNAME
      # - homepage.widget.type=generic
      # - homepage.widget.url=http://airdcpp:5600
      # - homepage.weight=2
