services:
  # Baikal - Users, Address Books, Calendars  
  baikal:
    image: ckulka/baikal:nginx
    container_name: baikal
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "all"]
    networks:
      - t3_proxy
    # ports:
    #   - "80:80"
    volumes:
      - $DOCKERDIR/appdata/baikal/config:/var/www/baikal/config
      - $DOCKERDIR/appdata/baikal/data:/var/www/baikal/Specific
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.cname-rtr-bypass.entrypoints=websecure"
      - "traefik.http.routers.cname-rtr-bypass.rule=Host(`cname.$DOMAINNAME`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth for LunaSea on iOS
      - "traefik.http.routers.cname-rtr-bypass.priority=100"
      # HTTP Routers Auth
      - "traefik.http.routers.cname-rtr.entrypoints=websecure"
      - "traefik.http.routers.cname-rtr.rule=Host(`baikal.$DOMAINNAME`)"
      - "traefik.http.routers.cname-rtr.priority=99"
      # Middlewares
      # - "traefik.http.routers.cname-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.cname-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.cname-rtr.service=cname-svc"
      - "traefik.http.routers.cname-rtr-bypass.service=cname-svc"
      - "traefik.http.services.cname-svc.loadbalancer.server.port=80" # this has to stay the name of the internal port used by the container, not the mapped port
      # UPDATE IMAGE - if watchtower should update this image - disable for risky stuff like IP configs
      - "com.centurylinklabs.watchtower.enable=true"