services:
  # eBook online manager
  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:latest
    # profiles: ["media", "arrs", "all"] # FOR FUTURE DEVELOPMENT
    networks:
      - t3_proxy
    
    security_opt:
      - no-new-privileges:true

    restart: unless-stopped

    ports:
      - $calibre_web_port:8083




    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    
    volumes:
      - $DOCKERDIR/appdata/calibre-web:/config
      - $MEDIADIR/Books/eBooks:/data
    
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth Bypass
      - "traefik.http.routers.calibre-web-rtr-bypass.entrypoints=websecure"
      - "traefik.http.routers.calibre-web-rtr-bypass.rule=Host(`calibre-web.$DOMAINNAME`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth for LunaSea on iOS
      - "traefik.http.routers.calibre-web-rtr-bypass.priority=100"
      # HTTP Routers Auth
      - "traefik.http.routers.calibre-web-rtr.entrypoints=websecure"
      - "traefik.http.routers.calibre-web-rtr.rule=Host(`calibre-web.$DOMAINNAME`)"
      - "traefik.http.routers.calibre-web-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.calibre-web-rtr-bypass.middlewares=chain-no-auth@file"
      #- "traefik.http.routers.calibre-web-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.calibre-web-rtr.service=calibre-web-svc"
      - "traefik.http.routers.calibre-web-rtr-bypass.service=calibre-web-svc"
      - "traefik.http.services.calibre-web-svc.loadbalancer.server.port=8083"
      # UPDATE IMAGE
      - "com.centurylinklabs.watchtower.enable=true"
      # Homepage Setup
      - homepage.group=Media Indexers
      - homepage.name=Calibre-Web
      - homepage.icon=calibre-web.png
      - homepage.href=http://calibre-web.shatteredcastle.com/
      - homepage.weight = 10
      # Homepage Widget Conf
      - homepage.widget.type=calibreweb
      - homepage.widget.url=http://calibre-web:8083
      - homepage.widget.username=admin
      - homepage.widget.password=admin123   

