services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns
    restart: unless-stopped
    environment:
      - CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
      - DOMAINS=$DOMAINNAME, $DOMAINNAME_EXT
      - PROXIED=false
      - IP6_PROVIDER=none
    cap_add:
      - NET_ADMIN