services:
  # FileFlows is for file management and changes.
  # https://fileflows.com/
  fileflows:
    container_name: fileflows
    image: revenz/fileflows
    
    restart: unless-stopped
    # ports:
    #   - $fileflows_port:5000
    networks:
      - t3_proxy
      - default
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $DOCKERDIR/appdata/fileflows:/temp
      - $USERDIR/synology:/app/Data
      - $DOCKERDIR/appdata/logs/hs/fileflows:/app/Logs
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.fileflows-rtr.entrypoints=websecure"
      - "traefik.http.routers.fileflows-rtr.rule=Host(`fileflows.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.fileflows-rtr.middlewares=chain-oauth@file"
      # - "traefik.http.routers.authelia-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.fileflows-rtr.service=fileflows-svc"
      - "traefik.http.services.fileflows-svc.loadbalancer.server.port=5000"
      # UPDATE IMAGE
      - "com.centurylinklabs.watchtower.enable=true"
      # Homepage Setup
      - homepage.group=Home Server
      - homepage.name=FileFlows
      - homepage.icon=fileflows.png
      - homepage.href=http://fileflows.$DOMAINNAME
      # - homepage.description=Media server
      - homepage.widget.type=fileflows
      - homepage.widget.url=http://fileflows:5000
