services:
  # Glances - System Information
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["monitoring", "all"]
    # privileged: true # Only for VM
    networks:
      - t3_proxy
      - socket_proxy
      - default
    # ports:
    #   - "61208:61208"
    pid: host
    volumes:
      # - $DOCKERDIR/appdata/glances/glances.conf:/glances/conf/glances.conf # Use this if you want to add a glances.conf file
      - $DOCKERDIR:/data/docker:ro
      
      # - /var/run/docker.sock:/var/run/docker.sock:ro # Use Docker Socket Proxy instead for improved security
    environment:
      # - GLANCES_OPT=-w -C /glances/conf/glances.conf --quiet --export influxdb
      - GLANCES_OPT=--export influxdb
      - GLANCES_OPT=-w
      - DOCKER_HOST=tcp://socket-proxy:2375
      - INFLUXDB_HOST=influxdb  # 👈 change from localhost
      - INFLUXDB_PORT=8086
      - INFLUXDB_USER=your_user
      - INFLUXDB_PASSWORD=your_pass
      - INFLUXDB_DB=glances
    

    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.glances-rtr-bypass.entrypoints=websecure"
      - "traefik.http.routers.glances-rtr-bypass.rule=Host(`glances.$DOMAINNAME`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth for LunaSea on iOS
      - "traefik.http.routers.glances-rtr-bypass.priority=100"
      # HTTP Routers Auth
      - "traefik.http.routers.glances-rtr.entrypoints=websecure"
      - "traefik.http.routers.glances-rtr.rule=Host(`glances.$DOMAINNAME`)"
      - "traefik.http.routers.glances-rtr.priority=99"
      # Middlewares
      # - "traefik.http.routers.glances-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.glances-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.glances-rtr.service=glances-svc"
      - "traefik.http.routers.glances-rtr-bypass.service=glances-svc"
      - "traefik.http.services.glances-svc.loadbalancer.server.port=61208" # this has to stay the name of the internal port used by the container, not the mapped port
      # UPDATE IMAGE - if watchtower should update this image - disable for risky stuff like IP configs
      - "com.centurylinklabs.watchtower.enable=true"
      # Homepage Setup - if this should be included on Homepage
      # - homepage.group=Monitor # set group name to whatever works
      # - homepage.name=Glances
      # - homepage.icon=glances.png
      # - homepage.href=http://glances.$DOMAINNAME
      # - homepage.weight=0
      # # Homepage Widget Setup
      # - homepage.widget.type=glances
      # - homepage.widget.url=http://glances:61208 # again, internal port for the container
      # - homepage.widget.version=4
      # - homepage.widget.metric=cpu
      # - homepage.widget.diskUnits=bytes
      # - homepage.widget.refreshInterval=5000
      # - homepage.widget.pointsLimit=15
      # # - homepage.widget.key=$glances_api_key   
