services:
  # Grocy - ERP System for the Kitchen
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "all"]
    networks:
      - t3_proxy
    # ports:
    #  - "$GROCY_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/grocy:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ

    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth
      - "traefik.http.routers.grocy-rtr.entrypoints=websecure"
      - "traefik.http.routers.grocy-rtr.rule=Host(`grocy.$DOMAINNAME`)"
      # Middlewares
      # - "traefik.http.routers.grocy-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.grocy-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.grocy-rtr.service=grocy-svc"
      - "traefik.http.routers.grocy-rtr-bypass.service=grocy-svc"
      - "traefik.http.services.grocy-svc.loadbalancer.server.port=80" # this has to stay the name of the internal port used by the container, not the mapped port
      # UPDATE IMAGE - if watchtower should update this image - disable for risky stuff like IP configs
      - "com.centurylinklabs.watchtower.enable=true"