services:  
  handbrake: # HandBrake - GUI Transcoder
    image: jlesage/handbrake
    container_name: handbrake
    networks:
      - default
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    ports:
      - "5800:5800"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 022
      KEEP_APP_RUNNING: 1
    volumes:
      - $DOCKERDIR/appdata/handbrake:/config
      - $MEDIADIR:/storage             # Read-only input media
      # - $MEDIADIR/transcoded:/output
      - /dev/shm:/tmp                     # Optional: Offload temp transcoding to RAM
    labels:
      - "traefik.enable=true"

      # Local routing
      - "traefik.http.routers.handbrake-rtr.rule=Host(`handbrake.$DOMAINNAME`)"
      - "traefik.http.routers.handbrake-rtr.entrypoints=websecure"
      - "traefik.http.routers.handbrake-rtr.service=handbrake-svc"
      - "traefik.http.routers.handbrake-rtr-bypass.middlewares=chain-oauth@file"

      # HTTP Service
      - "traefik.http.services.handbrake-svc.loadbalancer.server.port=5800"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
