services:
  # Home Assistant Core - Home Automation
  # Added temporarily since HASS.io (Home Assistant Supervised) on Docker has been deprecated.
  homeassistant:
    container_name: home-assistant
    restart: unless-stopped
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    # networks:
    #   - t3_proxy
    #   - host
    #   devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    #   - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    volumes:
      - $DOCKERDIR/appdata/homeassistant:/config
      - $DOCKERDIR/appdata/homeassistant/media:/media
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      #- /media/ssd/motioneye:/media/motioneye
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      ## Exclude From Watchtower
      - "com.centurylinklabs.watchtower.enable=false"
      ## Traefik
      - "traefik.enable=false"
      # # HTTP Routers
      # - "traefik.http.routers.ha-rtr.entrypoints=websecure"
      # - "traefik.http.routers.ha-rtr.rule=Host(`ha.$DOMAINNAME`)"
      # - "traefik.http.routers.ha-rtr.tls=true"
      # - "traefik.http.routers.ha-rtr.service=ha-svc"
      # # HTTP Services
      # - "traefik.http.services.ha-svc.loadbalancer.server.port=8123"
      # # Middlewares
      # - "traefik.http.routers.ha-rtr.middlewares=chain-no-auth@file"
