services:
  # Home Assistant Core - Home Automation
  # Added temporarily since HASS.io (Home Assistant Supervised) on Docker has been deprecated.
  homeassistant:
    container_name: home-assistant
    restart: unless-stopped
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    #    networks:
    #      - t3_proxy
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    #   - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    volumes:
      - $DOCKERDIR/appdata/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      #- /media/ssd/motioneye:/media/motioneye
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      ## Exclude From Watchtower
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"

      # HTTP Router
      - "traefik.http.routers.homeassistant-rtr.entrypoints=websecure"
      - "traefik.http.routers.homeassistant-rtr.rule=Host(`ha.$DOMAINNAME`)"

      # Optional Middleware Chain
      - "traefik.http.routers.homeassistant-rtr.middlewares=chain-no-auth@file"
      # or
      #- "traefik.http.routers.homeassistant-rtr.middlewares=chain-oauth@file"

      # Targeting the host directly
      - "traefik.http.routers.homeassistant-rtr.service=homeassistant-svc"
      - "traefik.http.services.homeassistant-svc.loadbalancer.server.url=http://$SERVER_IP:8123"

  # # Home Assistant Core - Home Automation
  # # If you want Home Assistant, use the one above. This is was old setup. I am still migrating things from this one to Home Assistant Core Above.
  # # Added temporarily since HASS.io (Home Assistant Supervised) on Docker has been deprecated.
  # hassio:
  #   container_name: hassio
  #   restart: unless-stopped
  #   image: homeassistant/home-assistant:0.111.0
  #   networks:
  #     - t3_proxy
  #   devices:
  #     - /dev/ttyUSB0:/dev/ttyUSB0
  #     - /dev/ttyUSB1:/dev/ttyUSB1
  #     - /dev/ttyACM0:/dev/ttyACM0
  #   ports:
  #     - target: 8123
  #       published: $home_assistant_port
  #       protocol: tcp
  #       mode: host
  #   privileged: true
  #   volumes:
  #     - $USERDIR/docker/hassio/homeassistant:/config
  #     - /etc/localtime:/etc/localtime:ro
  #     - $USERDIR/docker/shared:/shared
  #     - $USERDIR/docker/open-zwave:/open-zwave
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - TZ=$TZ
  #   labels:
  #     ## Exclude From Watchtower
  #     - "com.centurylinklabs.watchtower.enable=false"