services:
  # Home Assistant Core - Home Automation
  # Added temporarily since HASS.io (Home Assistant Supervised) on Docker has been deprecated.
  homeassistant:
    container_name: home-assistant
    restart: unless-stopped
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    #    networks:
    #      - t3_proxy
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    #   - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    volumes:
      - $DOCKERDIR/appdata/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      #- /media/ssd/motioneye:/media/motioneye
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      ## Exclude From Watchtower
      - "com.centurylinklabs.watchtower.enable=false"
      
      - "traefik.enable=true"

      # HTTP Router
      - "traefik.http.routers.homeassistant-rtr.entrypoints=websecure"
      - "traefik.http.routers.homeassistant-rtr.rule=Host(`ha.$DOMAINNAME`)"

      # Optional Middleware Chain
      - "traefik.http.routers.homeassistant-rtr.middlewares=chain-no-auth@file"
      # or
      #- "traefik.http.routers.homeassistant-rtr.middlewares=chain-oauth@file"

      # Targeting the host directly
      - "traefik.http.routers.homeassistant-rtr.service=homeassistant-svc"
      - "traefik.http.services.homeassistant-svc.loadbalancer.server.url=http://$SERVER_IP:8123"