services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - ${DOCKERDIR}/appdata/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../../.env
    environment:
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=${IMMICH_DB_USER}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=${IMMICH_DB_NAME}
      - REDIS_HOSTNAME=immich_redis
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always
    networks:
      - t3_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.rule=Host(`photos.${DOMAINNAME}`)"
      - "traefik.http.routers.immich.service=immich"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "com.centurylinklabs.watchtower.enable=true"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${DOCKERDIR}/appdata/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../../.env
    environment:
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=${IMMICH_DB_USER}
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=${IMMICH_DB_NAME}
      - REDIS_HOSTNAME=immich_redis
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always
    networks:
      - default

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${DOCKERDIR}/appdata/immich/model-cache:/cache
    env_file:
      - ../../.env
    restart: always
    networks:
      - default

  immich-redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: always
    networks:
      - default

  immich-postgres:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - ../../.env
    environment:
      - POSTGRES_PASSWORD=${IMMICH_DB_PASSWORD}
      - POSTGRES_USER=${IMMICH_DB_USER}
      - POSTGRES_DB=${IMMICH_DB_NAME}
    volumes:
      - ${DOCKERDIR}/appdata/immich/postgres_v2:/var/lib/postgresql/data
    restart: always
    networks:
      - default
