services:
  # Jellyfin - Media Server
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    networks:
      - default
      - t3_proxy
    security_opt:
      - no-new-privileges:true
      - apparmor:unconfined

    restart: always
    # profiles: ["media", "all"]
    user: $PUID:$PGID
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
    ports:
      - "8096:8096"
      # - "8920:8920" # Emby also uses same port if running both
    environment:
      PGID: $PGID
      PUID: $PUID
      UMASK_SET: 022
      TZ: $TZ
      LIBVA_DRIVER_NAME: iHD
      LIBVA_DRIVERS_PATH: /usr/lib/x86_64-linux-gnu/dri
    group_add:
      - "992"
      - "44"

    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $MEDIADIR:/data/media:ro
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    labels:
      - "traefik.enable=true"
      # # External auth-required
      # - "traefik.http.routers.jellyfin-rtr.rule=Host(`jellyfin.shatteredcastle.com`)"
      # - "traefik.http.routers.jellyfin-rtr.entrypoints=websecure"
      # - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      # - "traefik.http.routers.jellyfin-rtr.priority=10"
      # - "traefik.http.routers.jellyfin-rtr.middlewares=chain-oauth@file"
      # - "traefik.http.routers.jellyfin-rtr.tls.options=default@file"

      # Local bypass
      - "traefik.http.routers.jellyfin-rtr-bypass.rule=Host(`jellyfin.$DOMAINNAME`)" # && (ClientIP(`127.0.0.1/32`) || ClientIP(`192.168.0.0/16`) || ClientIP(`10.0.0.0/8`) || ClientIP(`172.16.0.0/12`) || ClientIP(`192.168.90.0/24`) || ClientIP(`192.168.91.0/24`))"
      - "traefik.http.routers.jellyfin-rtr-bypass.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-rtr-bypass.service=jellyfin-svc"
      - "traefik.http.routers.jellyfin-rtr-bypass.priority=100"
      - "traefik.http.routers.jellyfin-rtr-bypass.middlewares=chain-no-auth@file,middlewares-websocket@file"
      - "traefik.http.routers.jellyfin-rtr-bypass.tls.options=tls-opts@file"
      # HTTP Services
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"
      # UPDATE IMAGE
      - "com.centurylinklabs.watchtower.enable=true"
      # Homepage Setup
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=http://jellyfin.$DOMAINNAME
      # - homepage.description=Media
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://jellyfin:8096
      - homepage.widget.key=c7df7458078649d1aa388e10e30113e2
      - homepage.widget.fields=["movies","tv"]