services:
  # Comic Book Indexer and Downloader
  # https://github.com/Casvt/Kapowarr?tab=readme-ov-file
 kapowarr:
    container_name: kapowarr
    image: mrcas/kapowarr:latest
    # profiles: ["media", "arrs", "all"]

    networks:
      - t3_proxy
    ports:
      # - $kapowarr_port:5656
      - 5656:5656
      
    security_opt:
      - no-new-privileges:true
      
    restart: unless-stopped
    
    volumes:
      - $DOCKERDIR/appdata/kapowarr:/config
      - $MEDIADIR/Comics:/comics-1
      - $DOWNLOADSDIR:/downloads
      - "/etc/localtime:/etc/localtime:ro"

    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
  
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth Bypass
      - "traefik.http.routers.kapowarr-rtr-bypass.entrypoints=websecure"
      - "traefik.http.routers.kapowarr-rtr-bypass.rule=Host(`kapowarr.$DOMAINNAME_HS`) && (Header(`X-Api-Key`, `$KAPOWARR_API_KEY`) || Query(`apikey`, `$KAPOWARR_API_KEY`))"
      - "traefik.http.routers.kapowarr-rtr-bypass.rule=Host(`kapowarr.$DOMAINNAME`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth for LunaSea on iOS
      - "traefik.http.routers.kapowarr-rtr-bypass.priority=100"
      # HTTP Routers Auth
      - "traefik.http.routers.kapowarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.kapowarr-rtr.rule=Host(`kapowarr.$DOMAINNAME`)"
      - "traefik.http.routers.kapowarr-rtr.priority=99"
      # Middlewares
      #- "traefik.http.routers.kapowarr-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.kapowarr-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.kapowarr-rtr.service=kapowarr-svc"
      - "traefik.http.routers.kapowarr-rtr-bypass.service=kapowarr-svc"
      - "traefik.http.services.kapowarr-svc.loadbalancer.server.port=5656"
      # UPDATE IMAGE
      - "com.centurylinklabs.watchtower.enable=true"
      # # Homepage Setup
      # - homepage.group=Media Indexers
      # - homepage.name=Kapowarr
      # - homepage.icon=kapowarr.png
      # - homepage.href=http://kapowarr.$DOMAINNAME
      # # - homepage.description=Media server
      # - homepage.widget.type=kapowarr
      # - homepage.widget.url=http://kapowarr:5656
      # # - homepage.widget.key=$KAPOWARR_API_KEY
      # - homepage.weight=3
