services:
  librum:
    image: ghcr.io/librum-reader/librum-server:latest
    hostname: librum
    container_name: librum
    ports:
      - 5000:5000
    networks:
      - librum
      - t3_proxy
    volumes:
      - librum:/var/lib/librum-server/librum_storage
    environment:
      - JWTValidIssuer=exampleIssuer          # Optional. You can leave it as-is
      - JWTKey=exampleOfALongSecretToken      # Optional. You can leave it as-is
      - SMTPEndpoint=smtp.example.com         # Example for Gmail: smtp.gmail.com:587
      - SMTPUsername=mailuser123              
      - SMTPPassword=smtpUserPassword123
      - SMTPMailFrom=mailuser123@example.com
      - DBConnectionString=Server=mariadb;port=3306;Database=librum;Uid=librum;Pwd=mariadb;
      - AdminEmail=admin@example.com          # Admin login username
      - AdminPassword=strongPassword123       # Admin login password
      #- OpenAIToken=                         # Optional. Generate here: https://platform.openai.com/api-keys
    restart: unless-stopped
    depends_on:
      librum_db:
        condition: service_healthy            # Ensures the DB is up before the server.
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth Bypass
      - "traefik.http.routers.librum-rtr-bypass.entrypoints=websecure"
      # - "traefik.http.routers.librum-rtr-bypass.rule=Host(`librum.$DOMAINNAME_HS`) && (Header(`X-Api-Key`, `$librum_API_KEY`) || Query(`apikey`, `$librum_API_KEY`))"
      - "traefik.http.routers.librum-rtr-bypass.rule=Host(`librum.$DOMAINNAME`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth for LunaSea on iOS
      - "traefik.http.routers.librum-rtr-bypass.priority=100"
      # HTTP Routers Auth
      - "traefik.http.routers.librum-rtr.entrypoints=websecure"
      - "traefik.http.routers.librum-rtr.rule=Host(`librum.$DOMAINNAME`)"
      - "traefik.http.routers.librum-rtr.priority=99"
      # Middlewares
      #- "traefik.http.routers.librum-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.librum-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.librum-rtr.service=librum-svc"
      - "traefik.http.routers.librum-rtr-bypass.service=librum-svc"
      - "traefik.http.services.librum-svc.loadbalancer.server.port=5000"

  librum_db:
    image: mariadb:latest
    hostname: mariadb
    container_name: librum_db
    networks:
      - librum
    volumes:
      - librum_db:/var/lib/mysql
    environment:
      - MARIADB_USER=librum
      - MARIADB_PASSWORD=mariadb
      - MARIADB_DATABASE=librum
      - MARIADB_ROOT_PASSWORD=mariadb
    restart: unless-stopped
    healthcheck:                              # Ensures the DB is up before the server.
      test: ["CMD", "mariadb-admin", "ping", "-u", "librum", "-p'mariadb'", "-h", "localhost"]
      interval: 20s
      timeout: 40s
      retries: 3
      start_period: 30s

networks:
  librum:
    name: "librum"

volumes:
  librum:
    name: "librum"
  librum_db:
    name: "librum_db"

