services:
  otbr:
    container_name: otbr
    image: ghcr.io/home-assistant/otbr:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - RCP_PORT=/dev/serial/by-id/usb-Nabu_Casa_Home_Assistant_Connect_ZBT-1_f08e63f65912f01198dbfd13773d9da9-if00-port0
    volumes:
      - /dev/serial/by-id/:/dev/serial/by-id/
    devices:
      - /dev/serial/by-id/usb-Nabu_Casa_Home_Assistant_Connect_ZBT-1_f08e63f65912f01198dbfd13773d9da9-if00-port0

  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - $DOCKERDIR/appdata/matter-server:/data
      - /run/dbus:/run/dbus:ro
