services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: always
    ports:
      - 9925:9000
    volumes:
      - ${DOCKERDIR}/appdata/mealie:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.${DOMAINNAME}
    networks:
      - t3_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.entrypoints=websecure"
      - "traefik.http.routers.mealie.rule=Host(`mealie.${DOMAINNAME}`)"
      - "traefik.http.routers.mealie.service=mealie"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
      - "com.centurylinklabs.watchtower.enable=true"
