services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - $DOCKERDIR/appdata/mosquitto/config:/mosquitto/config
      - $DOCKERDIR/appdata/mosquitto/data:/mosquitto/data
      - $DOCKERDIR/logs/mosquitto:/mosquitto/log
