services:
  openaudible:
    image: ghcr.io/lanjelin/openaudible-docker:latest
    container_name: openaudible
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      #- CUSTOM_USER=JohnDoe # optional, but recommended if exposing to -
      #- PASSWORD=a-safe-pw  # the internet without any other form of authentication
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - $OPEN_AUDIBLE_PORT1:3000 #http
      - $OPEN_AUDIBLE_PORT2:3001 #https
    volumes:
      - $DOCKERDIR/appdata/openaudible:/config
      - $MEDIADIR:/data
      - $DOWNLOADSDIR/Audiobook-Transcode:/trans_library
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.openaudible-rtr.entrypoints=websecure"
      - "traefik.http.routers.openaudible-rtr.rule=Host(`openaudible.$DOMAINNAME_HS`)"
      # Middlewares
      - "traefik.http.routers.openaudible-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.openaudible-rtr.service=openaudible-svc"
      - "traefik.http.services.openaudible-svc.loadbalancer.server.port=3000"
      # UPDATE IMAGE
      - "com.centurylinklabs.watchtower.enable=true"
