services:
  # Overseerr - Media Requests and Discovery for Plex
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "all"]
    networks:
      - t3_proxy
    # ports:
    #   - "$OVERSEERR_PORT:5055"
    volumes:
      - $DOCKERDIR/appdata/overseerr:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.overseer-rtr.entrypoints=websecure"
      - "traefik.http.routers.overseer-rtr.rule=Host(`overseer.$DOMAINNAME`)"
      # Middlewares
      # - "traefik.http.routers.cname-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.cname-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.overseer-rtr.service=overseer-svc"
      - "traefik.http.services.overseer-svc.loadbalancer.server.port=5055"