services:
  pangolin:
    image: fosrl/pangolin:1.6.2
    container_name: pangolin
    restart: unless-stopped
    networks:
      - pangolin_proxy
    volumes:
      - $DOCKERDIR/appdata/pangolin/data:/app/data
    ports:
      - 80:80         # 👈 Required for ACME challenges
      - 443:443       # 👈 Required for HTTPS routing
      - 51820:51820/udp  # WireGuard
      - 3002:3002     # Optional direct access to Next.js
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: 3s
      timeout: 3s
      retries: 15

  gerbil:
    image: fosrl/gerbil:1.0.0
    container_name: gerbil
    restart: unless-stopped
    networks:
      - pangolin_proxy
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - $DOCKERDIR/appdata/gerbil/config:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp