services:
  # Plex - Media Server
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    networks:
      t3_proxy:
        ipv4_address: $PLEX_SERVER_IP
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    #profiles: ["media", "all"]
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      #- "33400:33400/tcp"
    volumes:
      - $DOCKERDIR/appdata/plex:/config
      - $MEDIADIR/TV Shows:/tv
      - $MEDIADIR/Movies:/movies
      - $MEDIADIR/Books:/audiobooks
      #- $DATADIR/data2/media:/data/media2
      # - $DATADIR/media:/data/media
      #- $EXTDIR/ssd/downloads:/data/downloads
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    environment:
      TZ: $TZ
      HOSTNAME: "JamesPlex"
      PLEX_CLAIM_FILE: /run/secrets/plex_claim
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: "http://$PLEX_SERVER_IP:32400/,https://plex.$DOMAINNAME,http://$SERVER_IP:32400/"
      # ALLOWED_NETWORKS: $LOCAL_IPS
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.plex-rtr.entrypoints=websecure"
      - "traefik.http.routers.plex-rtr.rule=Host(`plex.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.plex-rtr.middlewares=chain-oauth@file"
      # - "traefik.http.routers.plex-rtr.middlewares=chain-noauth@file"
      # HTTP Services
      - "traefik.http.routers.plex-rtr.service=plex-svc"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
      # UPDATE IMAGE
      - "com.centurylinklabs.watchtower.enable=true"
      # Homepage Setup
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=http://plex.$DOMAINNAME
      # - homepage.description=Media server
      - homepage.widget.type=plex
      - homepage.widget.url=http://plex:32400
      - homepage.widget.key=$PLEX_SERVER_TOKEN
      - homepage.weight=0

    secrets:
      - plex_claim