services:
  # Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest # Use portainer-ce if you do no have a Business Edition license key
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["core", "all"]
    networks:
      - t3_proxy
      - socket_proxy
    # command: -H unix:///var/run/docker.sock # # Use Docker Socket Proxy instead for improved security
    command: -H tcp://socket-proxy:2375
    ports:
      - $portainer_port:9000
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock:ro # # Use Docker Socket Proxy instead for improved security
      - $DOCKERDIR/appdata/portainer/data:/data # Change to local directory if you want to save/transfer config locally
    environment:
      - TZ=$TZ
    labels:
      #- "traefik.enable=true"
      # HTTP Routers
      #- "traefik.http.routers.portainer-rtr.entrypoints=websecure"
      #- "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAINNAME_HS`)"
      # Middlewares
      #- "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      #- "traefik.http.routers.portainer-rtr.service=portainer-svc"
      #- "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.portainer-rtr.entrypoints=websecure"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAINNAME`)"
      # Middlewares
      #- "traefik.http.routers.portainer-rtr.middlewares=chain-no-auth@file"
      #- "traefik.http.routers.portainer-rtr.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # HTTP Services
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
      # UPDATE IMAGE
      - "com.centurylinklabs.watchtower.enable=true"
      # Homepage Setup
      - homepage.group=Home Server
      - homepage.name=Portainer
      - homepage.icon=portainer.png
      - homepage.href=http://portainer.shatteredcastle.com/
      # Homepage Widget Setup
      - homepage.widget.type=portainer
      - homepage.widget.url=http://portainer:9000
      - homepage.widget.env=1
      - homepage.widget.key=$PORTAINER_API_KEY
