services:
  # Prometheus - Database for sensor data
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - default
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["dbs", "all"]
    ports:
      - $prometheus_port:9090
    volumes:
      - $DOCKERDIR/appdata/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - $DOCKERDIR/appdata/prometheus/data:/prometheus
    user: $PUID:$PGID
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'