services:
  # Readarr Exporter - Readarr metrics for Prometheus
  readarr-exporter:
    image: ghcr.io/onedr0p/exportarr:latest
    container_name: readarr-exporter
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["all", "media", "arrs"]
    networks:
      - t3_proxy
    # ports:
    #   - "9707:9707"
    environment:
      PORT: 9707
      URL: "http://readarr:8787"
      APIKEY: $READARR_API_KEY
      ENABLE_ADDITIONAL_METRICS: TRUE
    command: ["readarr"]