services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    networks:
      - socket_proxy
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock # Removed: Using socket-proxy instead
    environment:  
      - WATCHTOWER_CLEANUP=true
      - DOCKER_API_VERSION=1.44
      - DOCKER_HOST=tcp://socket-proxy:2375  # Use socket-proxy for secure Docker API access
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=36000
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:asn4os6amz5edt5r2yue98s3fwgtm6@u6mn4p4s782tsnwrh7189s1jja111i
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
